# Generated by Django 3.2.9 on 2022-04-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='Blog',
        ),
    ]
